export const defaultOptions = {
  accessibilityLabel: null,
  animationDone: false,
  animationDuration: 500,
  animationName: 'default',
  buttonCallback: null,
  buttonText: null,
  customClasses: null,
  duration: 4000,
  hideCallback: null,
  message: "Ackbar snackbar: It's a snackbar!",
  showCallback: null,
  size: 'normal',
  type: 'auto',
  variant: 'default',
};
